project:
  type: website
  render: 
    - "*.qmd"
    - "*.md"
    - "blog/**/*.qmd"
    - "about/index.*qmd"
  # prerender:

website:
  title: "GeonWook"
  favicon: images/study.png
  site-url: https://gwook.blog
  repo-url: https://github.com/YoonGeonWook/GWook-com
  repo-actions:
    - source
    - edit
    - issue
  open-graph: true
  navbar:
    # title: gwook
    background: light
    right:
      - text: Blog
        file: index.qmd
      - text: About
        file: about/index.qmd
      - icon: github
        href: https://github.com/YoonGeonWook

format:
  html:
    author: "Yoon GeonWook"
    comments:
      utterances:
        repo: YoonGeonWook/GWook-com
    theme: my-theme.scss
    css: styles.css
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    mainfont: "Lato"
    monofont: "Fira Mono"
    footnotes-hover: true
    fontsize: 1em
    link-external-newwindow: true

