---
pagetitle: "Data Analysis Blog"
page-layout: full
title-block-banner: false

listing: 
  contents: blog
  feed: true
  sort-ui: true
  sort:
      - "date desc"
      - "title desc"
  type: default
  fields: [image, title, description, date, reading-time]
  categories: true
  date-format: "YYYY-MM-DD"
  page-size: 9
toc: false
toc-location: body
---

```{r write-redirects}
#| echo: false

blog <- list.dirs(
  path = here::here("blog"),
  full.names=FALSE,
  recursive = FALSE
)

# extract the slugs
slugs <- stringr::str_remove(blog, "\\d{4}-\\d{2}-\\d{2}-(?!\\d)")

# lines to insert to a netlify _redicrect file
redirects <- paste0("/", slugs, " ", "/blog/", blog)

# write the _redirect file
writeLines(redirects, here::here("_site", "_redirects"))
```

```{r write-tags}
#| echo: false

library(rvest)
library(xml2)

raw_html <- read_html(here::here("_site/index.html"))

length_tags <- raw_html %>% 
  html_nodes("#quarto-margin-sidebar > div > div") %>% 
  length()

all_tags <- sapply(seq_len(length_tags), function(x){
  html_nodes(raw_html, xpath = glue::glue('///*[@id="quarto-margin-sidebar"]/div/div[{x}]/text()')) %>% 
    html_text(trim = TRUE)
})

all_tags[all_tags != "All"] %>% 
  readr::write_lines(here::here("_data/unique_categories.txt"))
```
