{
  "hash": "679b0d1c98675dd882601e25505dfb60",
  "result": {
    "markdown": "---\ntitle: \"E-commerce 데이터 분석 (1)\"\ndescription: |\n  UCI Machine Learning Repository: Online Retail Dataset\ndate: 2023-12-03\ncategories: [machine learning, statistics]\nimage: ecommerce.jpg\npreview-links: true\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n::: {.cell}\n<style type=\"text/css\">\npre code, pre, code {\n  <!-- white-space: pre !important; -->\n  overflow-x: scroll !important;\n  <!-- word-break: keep-all !important; -->\n  <!-- word-wrap: initial !important; -->\n}\n</style>\n:::\n\n\n본 포스팅은 패스트캠퍼스 [50개 프로젝트로 완벽하게 끝내는 머신러닝 시그니쳐](https://fastcampus.co.kr/data_online_msignature)의 강의내용을 바탕으로 참고하여 작성하였습니다.\n\n![문제해결 프로세스 7단계](seven-step-problem-solving-process.png){#fig-1}\n\n# 01. 문제해결 프로세스 기획 {#sec-1}\n\n패스트캠퍼스 강의 중 박지환 강사님께서 준비 해주신 이커머스 데이터 분석 예제를 참고하여 진행하였습니다. 주어진 문제의 시나리오는 아래와 같습니다.\n\n::: {.callout-note icon=\"false\"}\n### 시나리오\n\nA사는 이커머스 플랫폼을 운영하고 있다. 해당 이커머스 플랫폼 서비스가 성장하기 위해서는 3가지 조건이 필요하다.\n\n① 신규고객 유입 ② 유입 고객 재구매 ③ 재구매고객 충성 고객화\n\nA사는 현재 '① 신규교객 유입 활동'은 마케팅 비용을 투자하여 적극 수행하고 있으나, '② 유입 고객 재구매'이 미미한 상황이다. 충성고객의 Spending Power는 전체 매출에서 많은 비중을 차지하고 있으므로, 충성고객의 성장이 이어지지 않으면 플랫폼의 성장도 멈추게 되버린다.\n\n따라서 '② 유입 고객 재구매'를 촉진시킬 방법을 고민 중에 있는 상황이다.\n:::\n\n이 시나리오를 기반으로 문제해결 프로세스 @fig-1 에 따라 7가지 단계를 아래와 같이 정의할 수 있습니다.\n\n::: {.callout-note icon=\"false\"}\n### 문제해결 프로세스\n\n#### Step 1. 문제정의\n\n-   문제현상: 신규 고객 유입 후 재구매로 이어지는 고객의 감소\n-   예상 피해: `(재구매고객 → 충성고객)`의 부진으로 매출 성장 정체 및 신규고객 유입을 위한 마케팅 비용 증가로 인한 영업이익 감소\n\n#### Step 2. 기대효과\n\n-   재구매 고객 증가 → 충성 고객 증가 → 매출 성장 → 영업 이익 증가\n-   선순환 체계 구축으로 인한 서비스 성장\n\n#### Step 3. 해결방안\n\n-   ① EDA 및 일회성 데이터 분석을 통해 재구매 고객의 특성을 분석하고 이를 토대로 마케팅 기획\n-   ② 재구매 가능성이 높은 고객을 예측하는 모델링 후 이를 활용한 타겟 마케팅 진행\n\n#### Step 4. 우선순위\n\n-   ①번을 빠르게 수행 후 파일럿 테스트 진행 및 성과 측정\n-   ①번의 효과가 좋지 않다면, ②번 진행 후 파일럿 테스트 재실행\n\n#### Step 5. 데이터 분석\n\n-   결정된 우선순위에 따라서 데이터 분석 및 모델링 진행\n\n#### Step 6. 성과측정\n\n-   최종 마케팅 후 성능을 평가하기 위한 지표 수립\n-   분석 및 모델링을 통해 추출한 타겟 고객군과 대조군을 설정하여 A/B 테스트 수행\n-   A/B 테스트 결과 마케팅(재구매) 반응률 비교를 통해 통계적으로 유의미한지 검증: `t-test`\n-   유의미한 결과를 얻을 때까지 파일럿 테스트를 수정하며 진행\n\n#### Step 7. 모델 운영\n\n-   파일럿 테스트 후 결과가 유의미하다면 정규 마케팅으로 운영하기 위한 작업 준비\n-   모델을 실행을 위한 주기와 추출 타겟 고객군의 범위 결정\n-   정해진 주기에 따라 타겟 고객군의 추출을 자동화\n-   이를 마케팅 시스템과 연계하여 타겟 마케팅을 주기적으로 운영 및 평가\n:::\n\n현재 Step 1\\~4의 단계가 완료되어 **데이터 분석을 수행**해야 하는 단계라고 간주하겠습니다.\n\n# 02. Data Readiness Check & Sampling {#sec-2}\n\n사용하고자 하는 데이터는 [UCI Machine Learning Repository](https://archive.ics.uci.edu/)에서 제공하는 [Online Retail](https://archive.ics.uci.edu/datasets?search=Online+Retail) 데이터를 사용해 진행했습니다.\n\n이 Online Retail 데이터를 A사에서 수집한 고객 거래 이력 데이터로 간주하고 해당 데이터에 대한 기본적인 전처리를 수행하겠습니다.\n\n## 02-01. Data Info Check\n\n주어진 데이터는 e-commerce 온라인 구매 데이터로 데이터 명세표는 아래와 같습니다.\n\n| `InvoiceNo` | `StockCode` | `Description` | `Quantity` | `InvoiceDate` | `UnitPrice` | `CustomerID` |  `Country`  |\n|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|\n|  송장번호   |  재고코드   |   상세설명    |    수량    |   송장날짜    |  개당가격   |    고객ID    |    국가     |\n| Categorical | Categorical |  Categorical  |  Integer   |     Date      | Continuous  | Categorical  | Categorical |\n\n이제 수집된 데이터의 기본적인 정보를 확인해 보겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ndf <- read_csv(\"Online Retail.csv\", col_types = \"ccciTdcc\")\ndf %>% head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 8\n  InvoiceNo StockCode Description                           Quantity InvoiceDate         UnitPrice CustomerID Country       \n  <chr>     <chr>     <chr>                                    <int> <dttm>                  <dbl> <chr>      <chr>         \n1 489434    85048     \"15CM CHRISTMAS GLASS BALL 20 LIGHTS\"       12 2009-12-01 07:45:00      6.95 13085      United Kingdom\n2 489434    79323P    \"PINK CHERRY LIGHTS\"                        12 2009-12-01 07:45:00      6.75 13085      United Kingdom\n3 489434    79323W    \"WHITE CHERRY LIGHTS\"                       12 2009-12-01 07:45:00      6.75 13085      United Kingdom\n4 489434    22041     \"RECORD FRAME 7\\\" SINGLE SIZE\"              48 2009-12-01 07:45:00      2.1  13085      United Kingdom\n5 489434    21232     \"STRAWBERRY CERAMIC TRINKET BOX\"            24 2009-12-01 07:45:00      1.25 13085      United Kingdom\n6 489434    22064     \"PINK DOUGHNUT TRINKET POT\"                 24 2009-12-01 07:45:00      1.65 13085      United Kingdom\n```\n:::\n:::\n\n\n#### **Data 크기 확인**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1,067,370 rows & 8 cols\ndf %>% dim()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1067370       8\n```\n:::\n:::\n\n\n#### **Data type 확인**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1,067,370\nColumns: 8\n$ InvoiceNo   <chr> \"489434\", \"489434\", \"489434\", \"489434\", \"489434\", \"489434\", \"489434\", \"489434\", \"489435\", \"489435\", \"489435\", \"489435\", \"489436\", \"489436\", \"489436\", \"489436\", \"489436\", \"489436\"…\n$ StockCode   <chr> \"85048\", \"79323P\", \"79323W\", \"22041\", \"21232\", \"22064\", \"21871\", \"21523\", \"22350\", \"22349\", \"22195\", \"22353\", \"48173C\", \"21755\", \"21754\", \"84879\", \"22119\", \"22142\", \"22296\", \"222…\n$ Description <chr> \"15CM CHRISTMAS GLASS BALL 20 LIGHTS\", \"PINK CHERRY LIGHTS\", \"WHITE CHERRY LIGHTS\", \"RECORD FRAME 7\\\" SINGLE SIZE\", \"STRAWBERRY CERAMIC TRINKET BOX\", \"PINK DOUGHNUT TRINKET POT\",…\n$ Quantity    <int> 12, 12, 12, 48, 24, 24, 24, 10, 12, 12, 24, 12, 10, 18, 3, 16, 3, 12, 12, 12, 16, 4, 2, 12, 12, 12, 3, 6, 8, 8, 24, 6, 6, 12, 2, 1, 2, 2, 2, 3, 12, 12, 6, 3, 12, 12, 12, 12, 6, 6…\n$ InvoiceDate <dttm> 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-0…\n$ UnitPrice   <dbl> 6.95, 6.75, 6.75, 2.10, 1.25, 1.65, 1.25, 5.95, 2.55, 3.75, 1.65, 2.55, 5.95, 5.45, 5.95, 1.69, 6.95, 1.45, 1.65, 1.65, 3.39, 3.75, 8.50, 4.65, 2.10, 2.10, 5.95, 2.95, 1.25, 1.25…\n$ CustomerID  <chr> \"13085\", \"13085\", \"13085\", \"13085\", \"13085\", \"13085\", \"13085\", \"13085\", \"13085\", \"13085\", \"13085\", \"13085\", \"13078\", \"13078\", \"13078\", \"13078\", \"13078\", \"13078\", \"13078\", \"13078\"…\n$ Country     <chr> \"United Kingdom\", \"United Kingdom\", \"United Kingdom\", \"United Kingdom\", \"United Kingdom\", \"United Kingdom\", \"United Kingdom\", \"United Kingdom\", \"United Kingdom\", \"United Kingdom\"…\n```\n:::\n:::\n\n\n#### **변수별 결측치 확인**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% is.na() %>% colSums()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  InvoiceNo   StockCode Description    Quantity InvoiceDate   UnitPrice  CustomerID     Country \n          0           0        4382           0           0           0      243007           0 \n```\n:::\n:::\n\n\n고객 식별 정보인 `CustomerID` 같은 변수에 결측치가 있는 경우에는 추후에 해당 고객에 대한 정보를 알 수 없으므로 사전에 정보를 알 수 없는 불분명한 데이터로 취급하여 삭제하는 것이 좋습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>% drop_na(\"CustomerID\")\ndf %>% is.na() %>% colSums()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  InvoiceNo   StockCode Description    Quantity InvoiceDate   UnitPrice  CustomerID     Country \n          0           0           0           0           0           0           0           0 \n```\n:::\n:::\n\n\n#### **Outlier 확인**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% \n  select_if(is.numeric) %>% \n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Quantity           UnitPrice       \n Min.   :-80995.00   Min.   :    0.00  \n 1st Qu.:     2.00   1st Qu.:    1.25  \n Median :     5.00   Median :    1.95  \n Mean   :    12.41   Mean   :    3.68  \n 3rd Qu.:    12.00   3rd Qu.:    3.75  \n Max.   : 80995.00   Max.   :38970.00  \n```\n:::\n:::\n\n\n구매 수량을 나타내는 `Quantity`는 음수 값을 가질 수 없으나, 반품 물품에 대한 값이 있으므로 확인 후 처리해야 합니다. 여기서는 `Quantity`가 음수인 값은 이상치(Outlier)라고 간주하고 삭제하겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quantity가 음수인 데이터 확인 \n# 반품 및 회수 물량일 수도 있음\ndf %>% filter(Quantity < 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 18,744 × 8\n   InvoiceNo StockCode Description                       Quantity InvoiceDate         UnitPrice CustomerID Country       \n   <chr>     <chr>     <chr>                                <int> <dttm>                  <dbl> <chr>      <chr>         \n 1 C489449   22087     PAPER BUNTING WHITE LACE               -12 2009-12-01 10:33:00      2.95 16321      Australia     \n 2 C489449   85206A    CREAM FELT EASTER EGG BASKET            -6 2009-12-01 10:33:00      1.65 16321      Australia     \n 3 C489449   21895     POTTING SHED SOW 'N' GROW SET           -4 2009-12-01 10:33:00      4.25 16321      Australia     \n 4 C489449   21896     POTTING SHED TWINE                      -6 2009-12-01 10:33:00      2.1  16321      Australia     \n 5 C489449   22083     PAPER CHAIN KIT RETRO SPOT             -12 2009-12-01 10:33:00      2.95 16321      Australia     \n 6 C489449   21871     SAVE THE PLANET MUG                    -12 2009-12-01 10:33:00      1.25 16321      Australia     \n 7 C489449   84946     ANTIQUE SILVER TEA GLASS ETCHED        -12 2009-12-01 10:33:00      1.25 16321      Australia     \n 8 C489449   84970S    HANGING HEART ZINC T-LIGHT HOLDER      -24 2009-12-01 10:33:00      0.85 16321      Australia     \n 9 C489449   22090     PAPER BUNTING RETRO SPOTS              -12 2009-12-01 10:33:00      2.95 16321      Australia     \n10 C489459   90200A    PURPLE SWEETHEART BRACELET              -3 2009-12-01 10:44:00      4.25 17592      United Kingdom\n# ℹ 18,734 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quantity 음수값 제거\ndf <- df %>% filter(Quantity > 0)\n```\n:::\n\n\n#### **중복 데이터 확인**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% \n  mutate(duplicated = duplicated(.)) %>% \n  count(duplicated)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  duplicated      n\n  <lgl>       <int>\n1 FALSE      779494\n2 TRUE        26125\n```\n:::\n\n```{.r .cell-code}\n# 중복 데이터 확인\ndf %>% \n  filter(duplicated(df) | duplicated(df, fromLast = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 50,838 × 8\n   InvoiceNo StockCode Description                       Quantity InvoiceDate         UnitPrice CustomerID Country       \n   <chr>     <chr>     <chr>                                <int> <dttm>                  <dbl> <chr>      <chr>         \n 1 489517    21913     VINTAGE SEASIDE JIGSAW PUZZLES           1 2009-12-01 11:34:00      3.75 16329      United Kingdom\n 2 489517    21912     VINTAGE SNAKES & LADDERS                 1 2009-12-01 11:34:00      3.75 16329      United Kingdom\n 3 489517    21821     GLITTER STAR GARLAND WITH BELLS          1 2009-12-01 11:34:00      3.75 16329      United Kingdom\n 4 489517    22319     HAIRCLIPS FORTIES FABRIC ASSORTED       12 2009-12-01 11:34:00      0.65 16329      United Kingdom\n 5 489517    22130     PARTY CONE CHRISTMAS DECORATION          6 2009-12-01 11:34:00      0.85 16329      United Kingdom\n 6 489517    21912     VINTAGE SNAKES & LADDERS                 1 2009-12-01 11:34:00      3.75 16329      United Kingdom\n 7 489517    21491     SET OF THREE VINTAGE GIFT WRAPS          1 2009-12-01 11:34:00      1.95 16329      United Kingdom\n 8 489517    22130     PARTY CONE CHRISTMAS DECORATION          6 2009-12-01 11:34:00      0.85 16329      United Kingdom\n 9 489517    22319     HAIRCLIPS FORTIES FABRIC ASSORTED       12 2009-12-01 11:34:00      0.65 16329      United Kingdom\n10 489517    21913     VINTAGE SEASIDE JIGSAW PUZZLES           1 2009-12-01 11:34:00      3.75 16329      United Kingdom\n# ℹ 50,828 more rows\n```\n:::\n:::\n\n\n26,125개의 데이터가 중복되었음을 확인할 수 있습니다. 데이터의 정확성과 품질을 위해 중복 데이터를 삭제하겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 중복 삭제 후 재확인\ndf <- df %>% distinct()\ndf %>% \n  mutate(duplicated = duplicated(.)) %>% \n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n       n\n   <int>\n1 779494\n```\n:::\n:::\n\n\n이렇게 데이터에 대한 기본적인 정보와 전처리를 마치고 데이터의 형태를 보면 아래와 같이 기존 1,067,370개의 행에서 779,494개의 행으로 줄었습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1,067,370 → 779,494\ndf %>% dim()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 779494      8\n```\n:::\n:::\n\n\n## 02-03. Data Readiness Check\n\n데이터에 대한 기본 정보를 확인했으니 이제 현재 가지고 있는 데이터로 앞서 기획한 문제해결 프로세스를 적용할 수 있는지 점검해야 합니다.\n\n### (1) Target Label 생성\n\n당월 구매 고객이 다음 달에 재구매 시 해당 고객을 재구매 고객으로 정의하겠습니다. 예를들어, 2011년 01월에 구매한 고객이 2011년 02월에 구매를 한다면 해당 고객을 재구매 고객으로 정의하는 것입니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lubridate)\n\n# 기준년월 변수 생성: bsym - %Y-%m 형식\ndf <- df %>% mutate(bsym = format(InvoiceDate, \"%Y-%m\")) \n# 원본 데이터 저장: df_origin\ndf_origin <- df\n# 데이터 적재 기간 확인: 2009-12-01 ~ 2011-12-09 (약 2년)\nmin(df$InvoiceDate); max(df$InvoiceDate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"2009-12-01 07:45:00 UTC\"\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"2011-12-09 12:50:00 UTC\"\n```\n:::\n:::\n\n\n기본적인 전처리가 완료된 데이터를 `df_origin`으로 저장하여 보존하고, 이후 있을 전처리를 진행하겠습니다. Target label은 기준년월(`bsym`)과 고객(`CustomerID`)에만 영향을 받으므로 해당 두 변수를 고유하게 갖는 데이터로 재구성하겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>% distinct(bsym, CustomerID)\ndf %>% dim()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 25598     2\n```\n:::\n\n```{.r .cell-code}\ndf %>% head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  bsym    CustomerID\n  <chr>   <chr>     \n1 2009-12 13085     \n2 2009-12 13078     \n3 2009-12 15362     \n4 2009-12 18102     \n5 2009-12 12682     \n6 2009-12 18087     \n```\n:::\n:::\n\n\n2009년 12월부터 2011년 12월까지 연도 및 월(`bsym`)별로 당월 구매 고객이 내월 구매 고객일 경우 1을 갖는 `target` 변수(binary: 0,1)를 만들어 보겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 주어진 bsym에 구매 고객이 내월 구매 고객일 경우 1, 그렇지 않으면 0 값을 갖는 \n# target 변수 생성: process_bsym()\nprocess_bsym <- function(bsym_value, df) {\n  df_left <- filter(df, bsym == bsym_value)\n  bsym_1m <- ymd(paste0(bsym_value, \"-01\")) %m+% months(1) %>% format(\"%Y-%m\")\n  df_right <- df %>% \n    filter(bsym == bsym_1m) %>% \n    distinct(CustomerID) %>% \n    mutate(target = 1)\n  \n  df_merge <- left_join(df_left, df_right, by = \"CustomerID\") %>% \n    mutate(target = ifelse(is.na(target), 0, target))\n  \n  return(df_merge)\n}\n\n# 모든 bsym 값에 대해 process_bsym 함수 적용\ndf_all <- map_df(unique(df$bsym), ~process_bsym(.x, df))\ndf_all %>% head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  bsym    CustomerID target\n  <chr>   <chr>       <dbl>\n1 2009-12 13085           1\n2 2009-12 13078           1\n3 2009-12 15362           0\n4 2009-12 18102           1\n5 2009-12 12682           1\n6 2009-12 18087           1\n```\n:::\n:::\n\n\n### (2) Target Ratio 확인\n\n연도 및 월별로 재구매 고객 여부 변수 `target`의 비율을 확인해 보겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 기준년월 기준 Target ratio 확인\noptions(pillar.sigfig = 6)\ndf_target <- df_all %>% \n  group_by(bsym) %>% \n  reframe(total_y = sum(target),\n          count_y = n(),\n          ratio = total_y/count_y) \ndf_target %>% \n  print(n =  nrow(.))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 25 × 4\n   bsym    total_y count_y    ratio\n   <chr>     <dbl>   <int>    <dbl>\n 1 2009-12     337     955 0.352880\n 2 2010-01     262     720 0.363889\n 3 2010-02     314     774 0.405685\n 4 2010-03     378    1057 0.357616\n 5 2010-04     345     942 0.366242\n 6 2010-05     368     966 0.380952\n 7 2010-06     392    1041 0.376561\n 8 2010-07     351     928 0.378233\n 9 2010-08     365     911 0.400659\n10 2010-09     463    1145 0.404367\n11 2010-10     657    1497 0.438878\n12 2010-11     524    1607 0.326073\n13 2010-12     324     885 0.366102\n14 2011-01     262     741 0.353576\n15 2011-02     290     758 0.382586\n16 2011-03     304     974 0.312115\n17 2011-04     368     856 0.429907\n18 2011-05     410    1056 0.388258\n19 2011-06     365     991 0.368315\n20 2011-07     388     949 0.408851\n21 2011-08     425     935 0.454545\n22 2011-09     489    1266 0.386256\n23 2011-10     622    1364 0.456012\n24 2011-11     371    1665 0.222823\n25 2011-12       0     615 0       \n```\n:::\n:::\n\n\n현재 주어진 데이터는 2011년 12월이 마지막이기 때문에 내월이 없는 2011년 12월은 `target` 변수가 1 값을 가질 수 없습니다. 따라서 분석 대상에서 제외시키겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_target <- df_target %>% filter(bsym != '2011-12')\ndf_all <- df_all %>% filter(bsym != '2011-12')\ndf_target %>% \n  print(n = nrow(.))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 24 × 4\n   bsym    total_y count_y    ratio\n   <chr>     <dbl>   <int>    <dbl>\n 1 2009-12     337     955 0.352880\n 2 2010-01     262     720 0.363889\n 3 2010-02     314     774 0.405685\n 4 2010-03     378    1057 0.357616\n 5 2010-04     345     942 0.366242\n 6 2010-05     368     966 0.380952\n 7 2010-06     392    1041 0.376561\n 8 2010-07     351     928 0.378233\n 9 2010-08     365     911 0.400659\n10 2010-09     463    1145 0.404367\n11 2010-10     657    1497 0.438878\n12 2010-11     524    1607 0.326073\n13 2010-12     324     885 0.366102\n14 2011-01     262     741 0.353576\n15 2011-02     290     758 0.382586\n16 2011-03     304     974 0.312115\n17 2011-04     368     856 0.429907\n18 2011-05     410    1056 0.388258\n19 2011-06     365     991 0.368315\n20 2011-07     388     949 0.408851\n21 2011-08     425     935 0.454545\n22 2011-09     489    1266 0.386256\n23 2011-10     622    1364 0.456012\n24 2011-11     371    1665 0.222823\n```\n:::\n\n```{.r .cell-code}\ndf_target$ratio %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.2228  0.3623  0.3796  0.3784  0.4047  0.4560 \n```\n:::\n:::\n\n\n연도 및 월(`bsym`)별 `target`의 비율은 22.3% \\~ 45.6%의 값을 가지며, 대부분의 월에서 36% \\~ 40% 정도의 비율을 갖습니다. 전체 데이터의 `target`의 비율을 보면 아래와 같이 약 37.5% 정도의 내달 재구매 비율을 갖습니다. 이 정도의 class imbalance에 대해서는 over-sampling을 하지 않고 분석을 진행해도 괜찮을 것 같습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_all$target %>% mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3752151\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 마지막 행에 합계 추가\ndf_target <- df_target %>% \n  bind_rows(\n    tibble(bsym = \"total\",\n           total_y = sum(.$total_y),\n           count_y = sum(.$count_y),\n           ratio = 1)  \n)\n```\n:::\n\n\n## 02-03. Data Sampling\n\n![층화추출법](stratified-sampling.png){#fig-2}\n\n현재 `df_all`에는 약 25,000건의 데이터가 있지만, 만일 데이터가 1억건 정도로 매우 큰 경우 모델링을 하기엔 부담스러울 수 있습니다. 이럴 경우를 대비해 해당 데이터를 모집단으로 간주하고 샘플링을 통해 데이터를 줄일 수 있습니다.\n\n### Under-sampling: Stratified sampling\n\n관심 변수(`target`)에 대해 함께 살펴보고 싶은 변수가 있을 시(여기선 `bsym`), 해당 변수를 층화 변수로 두어 층화추출법(stratified sampling)을 실시할 수 있습니다. 샘플링 기법 중 하나인 층화추출법은 모집단을 층화 변수로 나눈 후 각 층/소집단 별로 독립적으로 표본을 뽑는 샘플링 방법입니다. 이로 인해 모집단 데이터에서 층화 변수와 관심 변수가 갖는 관계를 표본 데이터에서도 유지할 수 있다는 장점이 있습니다. 즉, 표본의 대표성을 확보할 수 있는 방법입니다.\n\n현재 `df_all` 데이터를 모집단 데이터로 간주하고, 표본 데이터를 뽑고자 합니다. 이때 층화추출법을 사용하기 위해선 우선적으로 각 층(`bsym`)별 표본 크기가 주어져야 합니다. 이 과정을 표본 배분(sample allocation)이라고 합니다. 여기에서는 모집단 `df_all`의 `bsym`별 층 크기를 유지하기 위해 비례 배분(proportional allocation)을 사용하겠습니다. 비례 배분에 따른 표본 데이터의 표본 층 크기는 아래와 같습니다.\n\n$$ \nn_h = n\\times\\frac{N_h}{\\sum_{l=1}^HN_l}\n$$\n\n`df_all` 데이터의 30%만 샘플링한다고 하겠습니다. 그럴 경우 필요한 층(`bsym`)별 표본 크기(`nh`)는 아래와 같습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 전체 데이터의 30%: 7495개\nround(nrow(df_all) * 0.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7495\n```\n:::\n\n```{.r .cell-code}\n# 모집단 층 크기: Nh, 표본 층 크기: nh\ndf_target <- df_target %>% \n  mutate(N = nrow(df_all)) %>% \n  mutate(n = round(nrow(df_all) * 0.3)) %>% \n  relocate(count_y, .after = n) %>% \n  rename(Nh = count_y) %>% \n  mutate(nh = round(n*Nh/N)) %>% \n  group_by(bsym)\n\ndf_target %>% print(n=25)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 25 × 7\n# Groups:   bsym [25]\n   bsym    total_y    ratio     N     n    Nh    nh\n   <chr>     <dbl>    <dbl> <int> <dbl> <int> <dbl>\n 1 2009-12     337 0.352880 24983  7495   955   287\n 2 2010-01     262 0.363889 24983  7495   720   216\n 3 2010-02     314 0.405685 24983  7495   774   232\n 4 2010-03     378 0.357616 24983  7495  1057   317\n 5 2010-04     345 0.366242 24983  7495   942   283\n 6 2010-05     368 0.380952 24983  7495   966   290\n 7 2010-06     392 0.376561 24983  7495  1041   312\n 8 2010-07     351 0.378233 24983  7495   928   278\n 9 2010-08     365 0.400659 24983  7495   911   273\n10 2010-09     463 0.404367 24983  7495  1145   344\n11 2010-10     657 0.438878 24983  7495  1497   449\n12 2010-11     524 0.326073 24983  7495  1607   482\n13 2010-12     324 0.366102 24983  7495   885   266\n14 2011-01     262 0.353576 24983  7495   741   222\n15 2011-02     290 0.382586 24983  7495   758   227\n16 2011-03     304 0.312115 24983  7495   974   292\n17 2011-04     368 0.429907 24983  7495   856   257\n18 2011-05     410 0.388258 24983  7495  1056   317\n19 2011-06     365 0.368315 24983  7495   991   297\n20 2011-07     388 0.408851 24983  7495   949   285\n21 2011-08     425 0.454545 24983  7495   935   281\n22 2011-09     489 0.386256 24983  7495  1266   380\n23 2011-10     622 0.456012 24983  7495  1364   409\n24 2011-11     371 0.222823 24983  7495  1665   500\n25 total      9374 1        24983  7495 24983  7495\n```\n:::\n\n```{.r .cell-code}\n# 반올림 때문에 표본 층 크기가 n=7495 보다 1개 더 크므로 \n# 2011년 11월 표본 크기를 한 개 줄여주자\ndf_target$nh[df_target$bsym=='2011-11'] <- df_target$nh[df_target$bsym=='2011-11'] - 1\n```\n:::\n\n\n이제 주어진 표본배분안에 따라 `bsym`별 30% 정도의 표본을 뽑아보겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nord <- unique(df_target$bsym)\nunits <- sampling::strata(df_all, stratanames = \"bsym\", size = df_target$nh[1:24], method=\"srswor\")\n\ndf_all_sample <- df_all %>% \n  slice(units$ID_unit)\ndf_all_sample %>% dim()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7495    3\n```\n:::\n:::\n\n\n이제 층화추출 후 표본 데이터 `df_all_sample`이 기존 모집단 데이터인 `df_all`의 `bsym` 별 `target`의 비율을 유지하는지 확인해 보겠습니다.\n\n\n::: {#tbl-1 .cell tbl-cap='연도 및 월별 재구매 비율: 표본 vs 모집단'}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(gt)\nlibrary(gtExtras)\ndf_tmp <- df_all_sample %>% \n  group_by(bsym) %>% \n  reframe(sum_y = sum(target),\n          nh = n())\n   \ndf_tmp2 <- df_tmp %>% \n  mutate(target_ratio = sum_y/nh,\n         target_ratio_pop = df_target$ratio[1:24]) %>% \n  pivot_longer(cols=c(target_ratio, target_ratio_pop), names_to = 'name') %>% \n  group_by(bsym) %>% \n  reframe(target_ratio = list(value))\ndf_tmp %>% left_join(df_tmp2, by='bsym') %>% \n  gt() %>% \n  gt_theme_nytimes() %>% \n  tab_header(title = \"bsym별 target 비율\") %>% \n  gt_plt_bar_stack(column = target_ratio, labels = c(\"target_ratio\", \"target_ratio_pop\"), palette = c(\"skyblue\", \"hotpink\"))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"uslucpqgry\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n@import url(\"https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n@import url(\"https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#uslucpqgry table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uslucpqgry thead, #uslucpqgry tbody, #uslucpqgry tfoot, #uslucpqgry tr, #uslucpqgry td, #uslucpqgry th {\n  border-style: none;\n}\n\n#uslucpqgry p {\n  margin: 0;\n  padding: 0;\n}\n\n#uslucpqgry .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uslucpqgry .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uslucpqgry .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uslucpqgry .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_bottom_border {\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_col_headings {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 1px;\n  border-bottom-color: #334422;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 12px;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uslucpqgry .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 12px;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uslucpqgry .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uslucpqgry .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uslucpqgry .gt_column_spanner {\n  border-bottom-style: none;\n  border-bottom-width: 1px;\n  border-bottom-color: #334422;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uslucpqgry .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uslucpqgry .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uslucpqgry .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uslucpqgry .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uslucpqgry .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uslucpqgry .gt_row {\n  padding-top: 7px;\n  padding-bottom: 7px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uslucpqgry .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uslucpqgry .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uslucpqgry .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uslucpqgry .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uslucpqgry .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uslucpqgry .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uslucpqgry .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uslucpqgry .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uslucpqgry .gt_table_body {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #FFFFFF;\n}\n\n#uslucpqgry .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uslucpqgry .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uslucpqgry .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uslucpqgry .gt_left {\n  text-align: left;\n}\n\n#uslucpqgry .gt_center {\n  text-align: center;\n}\n\n#uslucpqgry .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uslucpqgry .gt_font_normal {\n  font-weight: normal;\n}\n\n#uslucpqgry .gt_font_bold {\n  font-weight: bold;\n}\n\n#uslucpqgry .gt_font_italic {\n  font-style: italic;\n}\n\n#uslucpqgry .gt_super {\n  font-size: 65%;\n}\n\n#uslucpqgry .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uslucpqgry .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uslucpqgry .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uslucpqgry .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uslucpqgry .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uslucpqgry .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uslucpqgry .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style=\"font-family: 'Libre Franklin'; font-weight: 800;\">bsym별 target 비율</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"color: #A9A9A9; font-family: 'Source Sans Pro'; text-transform: uppercase;\" scope=\"col\" id=\"bsym\">bsym</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"color: #A9A9A9; font-family: 'Source Sans Pro'; text-transform: uppercase;\" scope=\"col\" id=\"sum_y\">sum_y</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"color: #A9A9A9; font-family: 'Source Sans Pro'; text-transform: uppercase;\" scope=\"col\" id=\"nh\">nh</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"color: #A9A9A9; font-family: 'Source Sans Pro'; text-transform: uppercase;\" scope=\"col\" id=\"&lt;span style='color:skyblue'&gt;&lt;b&gt;target_ratio&lt;/b&gt;&lt;/span&gt;||&lt;span style='color:hotpink'&gt;&lt;b&gt;target_ratio_pop&lt;/b&gt;&lt;/span&gt;\"><span style='color:skyblue'><b>target_ratio</b></span>||<span style='color:hotpink'><b>target_ratio_pop</b></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2009-12</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">111</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">287</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='103.76' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='103.76' y='0.0000000000000018' width='94.67' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='51.88' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.387</text><text x='151.09' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.353</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-01</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">79</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">216</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='99.46' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='99.46' y='0.0000000000000018' width='98.96' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.73' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3657</text><text x='148.94' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3639</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-02</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">78</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">232</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='89.92' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='89.92' y='0.0000000000000018' width='108.50' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='44.96' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.336</text><text x='144.17' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.406</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-03</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">116</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">317</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='100.35' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='100.35' y='0.0000000000000018' width='98.07' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='50.18' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3659</text><text x='149.39' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3576</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-04</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">103</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">283</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='98.90' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='98.90' y='0.0000000000000018' width='99.52' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.45' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3640</text><text x='148.66' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3662</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-05</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">107</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">290</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='97.63' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='97.63' y='0.0000000000000018' width='100.80' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='48.81' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.369</text><text x='148.03' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.381</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-06</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">131</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">312</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='104.61' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='104.61' y='0.0000000000000018' width='93.82' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='52.30' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.420</text><text x='151.52' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.377</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-07</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">102</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">278</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='97.70' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='97.70' y='0.0000000000000018' width='100.72' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='48.85' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.367</text><text x='148.06' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.378</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-08</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">108</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">273</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='98.58' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='98.58' y='0.0000000000000018' width='99.84' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.29' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3956</text><text x='148.50' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.4007</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-09</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">141</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">344</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='99.88' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='99.88' y='0.0000000000000018' width='98.54' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.94' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.4099</text><text x='149.16' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.4044</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-10</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">189</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">449</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='97.14' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='97.14' y='0.0000000000000018' width='101.28' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='48.57' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.421</text><text x='147.78' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.439</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-11</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">166</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">482</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='101.92' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='101.92' y='0.0000000000000018' width='96.50' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='50.96' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.344</text><text x='150.17' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.326</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2010-12</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">120</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">266</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='109.53' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='109.53' y='0.0000000000000018' width='88.89' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='54.77' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.451</text><text x='153.98' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.366</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-01</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">77</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">222</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='98.26' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='98.26' y='0.0000000000000018' width='100.17' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.13' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3468</text><text x='148.34' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3536</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-02</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">84</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">227</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='97.56' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='97.56' y='0.0000000000000018' width='100.87' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='48.78' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.370</text><text x='147.99' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.383</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-03</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">91</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">292</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='99.14' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='99.14' y='0.0000000000000018' width='99.29' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.57' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='35.83px' lengthAdjust='spacingAndGlyphs'>0.31164</text><text x='148.78' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='35.83px' lengthAdjust='spacingAndGlyphs'>0.31211</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-04</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">123</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">257</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='104.53' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='104.53' y='0.0000000000000018' width='93.90' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='52.27' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.479</text><text x='151.48' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.430</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-05</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">121</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">317</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='98.37' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='98.37' y='0.0000000000000018' width='100.06' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.18' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3817</text><text x='148.40' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3883</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-06</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">110</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">297</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='99.49' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='99.49' y='0.0000000000000018' width='98.94' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.74' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3704</text><text x='148.96' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.3683</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-07</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">114</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">285</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='98.13' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='98.13' y='0.0000000000000018' width='100.30' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='49.06' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.4000</text><text x='148.28' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='30.72px' lengthAdjust='spacingAndGlyphs'>0.4089</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-08</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">136</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">281</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='102.32' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='102.32' y='0.0000000000000018' width='96.10' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='51.16' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.484</text><text x='150.37' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.455</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-09</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">138</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">380</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='96.15' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='96.15' y='0.0000000000000018' width='102.27' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='48.08' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.363</text><text x='147.29' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.386</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-10</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">196</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">409</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='101.67' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='101.67' y='0.0000000000000018' width='96.75' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='50.84' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.479</text><text x='150.05' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.456</text></g></svg></td></tr>\n    <tr><td headers=\"bsym\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">2011-11</td>\n<td headers=\"sum_y\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">117</td>\n<td headers=\"nh\" class=\"gt_row gt_right\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\">499</td>\n<td headers=\"target_ratio\" class=\"gt_row gt_center\" style=\"font-family: 'Source Sans Pro'; font-weight: 400;\"><?xml version='1.0' encoding='UTF-8' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='198.43pt' height='14.17pt' viewBox='0 0 198.43 14.17'><defs>  <style type='text/css'><![CDATA[    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {      fill: none;      stroke: #000000;      stroke-linecap: round;      stroke-linejoin: round;      stroke-miterlimit: 10.00;    }    .svglite text {      white-space: pre;    }  ]]></style></defs><rect width='100%' height='100%' style='stroke: none; fill: none;'/><defs>  <clipPath id='cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw=='>    <rect x='0.00' y='0.00' width='198.43' height='14.17' />  </clipPath></defs><g clip-path='url(#cpMC4wMHwxOTguNDN8MC4wMHwxNC4xNw==)'><rect x='0.00' y='0.0000000000000018' width='101.74' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #87CEEB;' /><rect x='101.74' y='0.0000000000000018' width='96.69' height='14.17' style='stroke-width: 1.07; stroke: #FFFFFF; stroke-linecap: butt; stroke-linejoin: miter; fill: #FF69B4;' /><text x='50.87' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.234</text><text x='150.08' y='9.52' text-anchor='middle' style='font-size: 8.54px;fill: #FFFFFF; font-family: \"Arial\";' textLength='25.60px' lengthAdjust='spacingAndGlyphs'>0.223</text></g></svg></td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 표본 전체 target ratio: 38.1%\n# 모집단 전체 target ratio: 37.5%\ndf_all_sample$target %>% mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3813209\n```\n:::\n\n```{.r .cell-code}\ndf_all$target %>% mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3752151\n```\n:::\n:::\n\n\n이렇게 구성한 `df_all_sample` 데이터를 가지고 Data Mart를 만드는 과정을 다음 포스팅에서 다루겠습니다.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}